### ISSUE TITLE
Pythonインタプリタでのモデル等の取得について

### ISSUE THREAD

**Issue by kindsenior** [s-nakaoka/choreonoid#10]
Pythonインタプリタの使用法についての質問です．

choreonoid-1.5.0/sample/python/SR1Walk.py等を参考にしていて,
インタプリタにてWorldItemを新たに作成したりBodyItemのモデルファイルを新たにロードする方法は分かるのですが，既にchoreonoidのGUI操作等から作成・ロードしたItemを取得するにはどのようにすればいいでしょうか？

具体的には
c++のプラグインでいうと
```
ItemList<BodyItem> bodyItems = ItemTreeView::mainInstance()->checkedItems<BodyItem>();
body = bodyItems[0]->body();
```
のような操作をPythonインタプリタにて実行する方法を知りたいです．

**Comment by fkanehiro** [comment]
シーンビューを複数使っている場合に、上記の方法だとメイン（？）のビューにチェックの入ったアイテムだけが取得されるようですが、サブ（？）のビューでチェックが入っているアイテムを取得するにはどうしたらよいのでしょうか。

**Comment by s-nakaoka** [comment]
ItemTreeViewのcheckedItems関数は、元のC++ではidという引数があって、これでどの追加チェックを参照するかを指定できました。これがPythonラッパではうまく使えない状態だったようなので、そこを修正しました。例えば、

 ItemTreeView.instance().checkedItems(1)

とすれば、アイテムツリービューの右側に最初に追加されたチェックについて、チェックされているアイテムを取得できます。

ちなみに、シーンビューが３つ以上あってそれぞれチェックを追加する場合もあるでしょうし、今後追加のチェックは他の機能でも使うことがあり得ますので、本当はチェック番号をハードコーディングで書かないほうがよいです。まだ無いのですが、「対象のビューをビューの名前で取得」→「取得したビューの関数で対応するチェック番号を取得」といった流れでこれをできるようにしたいと思います。

ちなみに、取得するアイテムの型を

 checkedItems(BodyItem)

というかたちで指定する書き方は、今回いったん廃止とさせていただきました。
上記の改良とこのオーバーロードの両立について、できないことはないのですが、少し実装が面倒でしたので・・・。
型を限定したしたリストの取得は、上にもあるように、

 bodyItems = BodyItemList(ItemTreeView.instance().checkedItems())

という書き方でもできますので、そちらを使ってきただければと思います。
この方が両者で混乱しなくてすみますし。
