### ISSUE TITLE
シミュレーション中にロボットを強制的に座標を指定して移動させたい

### ISSUE THREAD

**Issue by YoheiKakiuchi** [s-nakaoka/choreonoid#103]
シミュレーション中にロボットを移動させる方法として、ルートリンクを右クリックして
移動マーカーを出して移動させる方法があります。
この方法ですと、移動座標を正確に入力するには少々時間がかかります。

座標を指定して、ロボットがその座標に強制的に移動するような、スクリプトなど方法は
ございますでしょうか？
（座標は任意の座標を指定できるとありがたいですが、シミュレーション初期値などの固定値でも構いません）

**Comment by s-nakaoka** [comment]
とりあえず、BodyLinkView上のリンク座標数値ボックスからの入力でもシミュレーション中の強制的な位置指定を行えるようにしました。まずシーンビュー上で移動用のマーカーを出した状態にして、対象となるロボットのルートリンクがBodyLinkViewの対象にもなっている状態（Linkビューでリンクを選択するか、シーンビュー上でリンクをダブルクリックする）で、数値を入力してください。

Pythonラッパを追加することで、スクリプトからも指定できると思います。そちらの方がよろしければ、そちらも対応します。

**Comment by YoheiKakiuchi** [comment]
確認できました。ありがとうございます。
