### ISSUE TITLE
ＯＤＥエンジンでCylinderプリミティブが干渉チェックの対象にならない？

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#117]
車輪をCylinderプリミティブを使って表現した車両のシミュレーションをODEシミュレータで行うと、車輪が床をすり抜けてしまいます。
ODEエンジンではCylinderプリミティブは干渉チェックの対象にならないのでしょうか？

**Comment by fkanehiro** [comment]
Cylinder対TrimeshがODEでサポートされていないから、ということですかね。
http://ode-wiki.org/wiki/index.php?title=Manual:_Collision_Detection

**Comment by fkanehiro** [comment]
と思いましたが床はBoxプリミティブでCylinder対Boxはサポートされているはずなので違いそうですね。

**Comment by hattorishizuko** [comment]
ODEのCｙlinder向きが９０度回転していたので修正しました。これでどうでしょうか。

**Comment by fkanehiro** [comment]
コミットが見当たらないのですが、どちらになりますでしょうか？

**Comment by fkanehiro** [comment]
すり抜けなくなりました。
ありがとうございます。
