### ISSUE TITLE
ソースコードからのビルドとインストールができない。

### ISSUE THREAD

**Issue by HiroshiIzumitani** [s-nakaoka/choreonoid#138]
はじめまして。大阪府立大学工業高等専門学校４年メカトロニクスコースの和泉谷です。

choreonoid HPに記載されている「ソースコードからのビルドとインストール (Ubuntu Linux編)」（　**http://choreonoid.org/ja/install/build-ubuntu.html#id6**　）
より、ここに記載されている通りに”CMake によるビルド設定”の”ccmake .”を実行し、 BUILD_GROBOT_PLUGIN を “ON” にしました。Press [c] to configureとあるように操作したのですが図のような画面になりこの先に進めません。
![screenshot from 2017-03-16 16-24-03](https://cloud.githubusercontent.com/assets/26453288/23985941/fca1fc58-0a64-11e7-8d92-2e88d6e51cbf.png)

何が原因かわからないのですが、このようになります。どのようにすればよいでしょうか。

以上です。

ご指導のほどおねがいします。

**Comment by s-nakaoka** [comment]
BUILD_OPENRTM_PLUGINがONになっていませんか？
このエラーメッセージからすると、OpenRTMがインストールされていないか、CMakeがそれをうまく見つけられていないように見えます。

**Comment by HiroshiIzumitani** [comment]
ありがとうございます。

試して見ます。

2017/03/16 19:58、s-nakaoka <notifications@github.com> のメッセージ:
