### ISSUE TITLE
IK拘束が有効になっているロボットの自由配置

### ISSUE THREAD

**Issue by haraisao** [s-nakaoka/choreonoid#147]
G-ROBOT,RIC30などIK拘束を有効にしているロボットモデルを利用すると、ロボットを自由に配置することができません。IK拘束の有効/無効ができればよいと思うのですが。どうするのが正しいやりかたなのでしょうか？

**Comment by s-nakaoka** [comment]
ロボット全体を動かしたいということでしょうか。
基本的には、ベースリンクとして設定したリンクをドラッグするとモデル全体が移動します。
ただし運動学モードが「プリセット運動学モード」の場合、IKになってしまう場合があります。
その場合は、運動学モードを「順運動学モード」か「逆運動学モード」にしてみてください。
http://choreonoid.org/ja/manuals/latest/handling-models/pose-editing.html#model-kinematics-mode
これで全体を動かせるのではないかと思います。

**Comment by haraisao** [comment]
どうもありがとうございます。動作が確認できました。
