### ISSUE TITLE
オプション→Scene View→干渉形状の表示がプロジェクトに保存されません

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#150]
オプション→Scene View→干渉形状の表示がプロジェクトに保存されません．Release-1.5のWindows版で試しています．その後のバージョンで直っているのであれば，対応するコミットを教えていただけないでしょうか．

**Comment by s-nakaoka** [comment]
この機能は1.5においては実験的なものであり、プロジェクト保存等までは作りこめていませんでした。

なお、開発版ではこの機能を強化しているところです。
シーンビューの設定ダイアログに、"Show collision visualization button set" というチェックが追加してありまして、このチェックを入れると、シーンビューのツールバーに干渉チェックと関連する表示の切り替えボタンが追加されます。
具体的には、V, F, C, 従来の干渉表示ボタン、と出てきます。
VはVisual=表示用モデル、CはCollision=干渉用モデルを意味しています。
FはFlipで、ボタンの状態を入れ替えます。
アイコン作るのに時間がかかるので、とりあえず上記ラベルをつけています。

また、新YAML形式モデルファイルでも、表示用、干渉用の切り分けができるようになりました。ドキュメントはまだありませんが、サンプルのPA10モデルで干渉用モデルを入れてみましたので、そのモデルファイル share/model/PA10/PA10.body を見ていただければ、書き方はだいたい分かるのではないかと思います。

ただし、開発版はここしばらくWindowsでのビルドや動作確認の検証が出来ていないので、お試しいただく場合はUbuntuを使ったほうがよいかと思います。
