### ISSUE TITLE
タイムバーの表示をオフ→オンをするとChoreonoidが落ちる

### ISSUE THREAD

**Issue by haraisao** [s-nakaoka/choreonoid#151]
ツールバーのうち「タイムバー」のみが、表示をオフにした後に、再度表示させようとするとChoreonoidが落ちてしまいます。これは、1.5および開発版でその現象を確認しています。バグではないでしょうか。

**Comment by s-nakaoka** [comment]
ご報告ありがとうございます。こちらの修正案件リストに入れておきます。

**Comment by s-nakaoka** [comment]
修正してもらいました。
63e5cea28ae69097acdf292796f54ec999965245
