### ISSUE TITLE
シミュレーション時のエラー

### ISSUE THREAD

**Issue by yukimorikane** [s-nakaoka/choreonoid#153]
先日アップデートを行い起動してみたところ今まで動いていたモデルが動かなくなりました。メッセージには
SimpleControllerのinitializeメソッドが失敗しました
と記述されているのですがこのことが原因と考えています。解決策があれば教えていただけませんか？
他のサンプルモデルのシミュレーションは問題なく動いていたためコンピュータに不具合があるとは思えません。

**Comment by s-nakaoka** [comment]
すみません、開発版ではSimpleControllerのAPIに少し変更が加えられています。
この件に直接関わる説明は以下にあります。
http://choreonoid.org/ja/manuals/latest/simulation/howto-implement-controller.html#body
また、SimpleControllerについては以下のチュートリアルもありますので、こちらもご覧いただけますでしょうか。
http://choreonoid.org/ja/manuals/latest/simulation/tank-tutorial/index.html

**Comment by yukimorikane** [comment]
返信が遅くなり申し訳ありません。ここにあるTankJoystickController.soというプログラムを書き換えるということでいいのでしょうか。
![image](https://user-images.githubusercontent.com/29052281/29152572-156910c4-7dc3-11e7-88a9-68c8ece93368.png)

**Comment by s-nakaoka** [comment]
すみませんが、ご質問の意図がよく分かりません。
何をしようとされているのか、もう少し具体的にお願いします。

**Comment by s-nakaoka** [comment]
ここも参考にしてみてください。
http://www.hyuki.com/writing/techask.html
