### ISSUE TITLE
ImageProvider.hの場所

### ISSUE THREAD

**Issue by haraisao** [s-nakaoka/choreonoid#155]
先日追加されたImageProviderクラスですが、このクラス定義がされているファイル（ImageProvider.h）は、src/Utilの下にあるのですが、実際に利用されているのは、CnoidBaseのファイル群になっています。そのため、CNOID_EXPORTがVC++では、定義されませんので、src/Baseの方に移動していただけないでしょうか？

現在のままですと、VC++でのビルドができません。

以上、よろしくお願いいたします。

**Comment by s-nakaoka** [comment]
SceneProviderと同様に、ImageProviderの実装をsrc/Util内でも行うようにしました。
1fea17eff35c6255748e5b1d41c4839b64af9c36

SceneProviderについてはこれでビルドできていたようですので、ImageProviderについてもこれでビルドできるのではないかと思います。

**Comment by haraisao** [comment]
修正を確認しました。VS2015で、ビルドできるようになりました。どうもありがとうございます。
