### ISSUE TITLE
4wheelsVehicleについて

### ISSUE THREAD

**Issue by yukimorikane** [s-nakaoka/choreonoid#156]
今私は自作のクレーン車を作成しています。そこでクレーン車を4輪で作成するためにサンプルモデルの4wheelsVehicleを参考にしようと思いました。まず、タイヤのサイズのみを全て0.2に変更しシミュレーションをしてみたところ図のような現象が発生しました。これはシミュレーションを始めてコントローラーは何もふれずに数秒たった後のものなのですが改善することは可能でしょうか。
![4bigwheel_sim](https://user-images.githubusercontent.com/29052281/29345086-42a869be-8277-11e7-8585-3c13647dfe8c.png)

**Comment by s-nakaoka** [comment]
元のモデルにはステアリングをつなぐロッドのリンクがありますが、その部分がこちらのモデルではうまく接続できていないのかもしれませんね。
