### ISSUE TITLE
Implementing Sample Controller for walking(like a preview controller)

### ISSUE THREAD

**Issue by miladsh** [s-nakaoka/choreonoid#157]
Hello,
I have started to use Choreonoid as a simulator for bipedal walking.
 I have tried most of the tutorial but the controller tutorial just tries to follow a preplanned desired position for joints. for example the SRI walk try to follow some preplanned angle joint, however I want to implement a walking controller on robot.
Is there any sample file for implementing a walking controller( such as preview control algorithm)?
Thanks in advance,
Milad

**Comment by s-nakaoka** [comment]
> Is there any sample file for implementing a walking controller( such as preview control algorithm)?

No, there is not.

Note that the preview control algorithm is usually used for generating preplanned desired joint trajectories like you mentioned, and then the trajectories are input to the walking controller that has a feedback stabilization control using some sensors such as force sensors, acceleration sensors, rate gyros.

For the preview control for biped walking, please refer to the following textbook:
http://www.springer.com/us/book/9783642545351
