### ISSUE TITLE
 Unknown CMake command "add_cnoid_simple_controller".  

### ISSUE THREAD

**Issue by piekah** [s-nakaoka/choreonoid#164]
中岡先生
大変お世話になっております．
cmakeコマンドを使用して、コントローラをコンパイルするときにエラーが出てしまいました．
以下はエラーメッセージでございます．

CMake Error at CMakeLists.txt:2 (add_cnoid_simple_controller):
  Unknown CMake command "add_cnoid_simple_controller".
-- Configuring incomplete, errors occurred!
See also "/home/choreonoid/ext/ball/CMakeFiles/CMakeOutput.log".

CMakeLists.txtの中身を何回も打ち直したが、このエラーが出てしまいます．解決方法を教えてください．

**Comment by s-nakaoka** [comment]
まず、先ほども書きましたが、ここはどなたでも参加可能な情報交換や議論の場であると考えています。必ず私が回答しなければならない場ではありませんので、特に理由がなければ、宛名等は書かずに、いきなり議論したいことだけを書いていただければ結構です。

本題に入りますと、この情報だけからは何が起きているのかよく分かりません。エラーメッセージの意味は分かるのですが、マニュアル通りに進めるとこのエラーにはならないはずなので、何をどのように進めようとしているかの情報がないとなんとも言えません。

そのあたりは以下のページも参考にしてみてください。
http://www.hyuki.com/writing/techask.html
（ただし、このページに書かれているとおりにやられても困るところがありますので、あくまで参考ということでお願いします。）
