### ISSUE TITLE
cnoid-nameserverでコンテキストの作成ができない

### ISSUE THREAD

**Issue by Nobu19800** [s-nakaoka/choreonoid#167]
cnoid-nameserverでネームサーバーを起動してRTCを登録しようとしたのですが、ネームサーバーにRTCが表示されません。

OpenRTM-aistのRTCはデフォルトでホスト名のコンテキストの下にRTCのオブジェクトを登録するのですが、cnoid-nameserverのnew_context関数の中で問題が発生しているようなので上手く動作しないようです。

**Comment by s-nakaoka** [comment]
今産総研内部でOpenRTM関連機能の改良をしようとしているところなので、この件もそちらで扱いたいと思います。

**Comment by s-nakaoka** [comment]
最新のmasterではcnoid-nameserverがコンテキストに対応しています。
