### ISSUE TITLE
モデルの移動軌跡の表示について

### ISSUE THREAD

**Issue by yukimorikane** [s-nakaoka/choreonoid#169]
サンプルのクローラモデルの中心等がどこを通ったかという情報を表示させることは可能でしょうか。

**Comment by s-nakaoka** [comment]
モデルの特定の箇所の軌跡を線か何かでシーンビュー上に表示したいとうことでしょうか。
今のところそのような機能はありません。プラグインを書けば実現できないことはないですが…。

**Comment by yukimorikane** [comment]
わかりました。返答ありがとうございます。
