### ISSUE TITLE
implementing an MPC for push recovery of a humanoid robot

### ISSUE THREAD

**Issue by MiladShafiee** [s-nakaoka/choreonoid#171]
Hello,
I have  imported a humanoid model in choreonoid and I implemented offline trajectory generation for bipedal walking.
Now I want to implement a push recovery controller based on  model predictive controller.
My algorithm has two part. 
One  part is for state estimation(that reads data of IMU and F/T sensors at each sample time and estimate the center of mass position based on kalman filter).
The second part of algorithm is  model predictive control  that needs to implement quadratic programming(QP) online.
Is it possible to implement this controller online on the simulated humanoid robot in choreonoid? 
Thanks in advance

**Comment by s-nakaoka** [comment]
I think it is possible to implement such a controller. However, this discussion is beyond the scope of the use and development of this software, so here I can not answer any more.
