### ISSUE TITLE
1.6.0はWindowsでビルドできますか？

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#177]
1.6.0のリリースおめでとうございます！
さて，1.6.0はWindowsのVisual Studioでビルドできるようになっていますか？

**Comment by hattorishizuko** [comment]
Visual Studio2015でビルドできることを確認しております。
http://choreonoid.org/ja/manuals/latest/install/build-windows.html
を参考にしてください。

OpenRTMを使われる場合は、USE_PYTHON３のチェックは外し方が、問題が起きにくいかと思います。

**Comment by y-masutani** [comment]
回答ありがとうございます．時間ができたらVS2012とVS2015で試してみたいと思います．

**Comment by hattorishizuko** [comment]
申し訳ありませんがVS2012では、ビルドできないと思います。
VS2013では試したのですが、VS2013がC++１１の機能に対応していない部分があって、ビルドできない状態です。

**Comment by y-masutani** [comment]
そういうこともあるかなと思い書いてみたのですが，お知らせいただきありがとうございます．時間を無駄にせずに済みました．
