### ISSUE TITLE
AGX Dynamicsでシミュレーションができない

### ISSUE THREAD

**Issue by taka40606** [s-nakaoka/choreonoid#195]
お世話になります。
開発版でAGX Dynamicsのプラグインをコンパイルし、
サンプルのプロジェクトを開いてAGX Dynamicsでシミュレーション開始すると、
「AGXSimulatorによるシミュレーションを開始しました。」
というメッセージは出ますが、0秒のまま時間が進みません。
この問題を解決する方法はございますでしょうか。

OSはUbuntu 16.04.3を使用しており、
AGX Dynamicsのversionは2.21.1.1と2.19.1.2で試してどちらも同じ結果となりました。

**Comment by m-shimizu** [comment]
開発版では，2.20.0.1は動作するとのことです．
https://www.choreonoid.org/redmine/projects/agx-dynamics-plugin/news

**Comment by taka40606** [comment]
バージョンを2.20.0.1にしたところ、動作するようになりました。
ありがとうございました。
