### ISSUE TITLE
シミュレーターにおいて考慮されている制限について

### ISSUE THREAD

**Issue by YoheiKakiuchi** [s-nakaoka/choreonoid#21]
シミュレータ上では、ロボットのモデルファイルに書いてある関節角度の制限の範囲外の角度になってしまっているようですが、これは正しい動作でしょうか？

また、シミュレータでは、モデルファイルに書いてある関節速度リミット、電流制限（から計算できる関節トルク制限）は考慮されていますでしょうか？

**Comment by s-nakaoka** [comment]
> シミュレータ上では、ロボットのモデルファイルに書いてある関節角度の制限の範囲外の角度になってしまっているようですが、これは正しい動作でしょうか？

これはシミュレーションエンジンによるのですが、AISTSimulatorItemでは、今のところ関節角度のリミットはかかりません。ODESimulatorItemでは、"Limit joint range" というプロパティを true にすると、シミュレーションでもリミットがかかります。

> また、シミュレータでは、モデルファイルに書いてある関節速度リミット、電流制限（から計算できる関節トルク制限）は考慮されていますでしょうか？

こちらもシミュレーションエンジンによりますが、今のところそれらを考慮してくれるエンジンはありません。HRP-2等のシミュレーションでは、トルク制限についてはコントローラ側で対処しているのが現状です。
