### ISSUE TITLE
Contact/Range Sensor problem while biped is walking

### ISSUE THREAD

**Issue by mohamadmahdavian** [s-nakaoka/choreonoid#225]
Hi

I am trying to use choreonoid for controlling a biped and I have attached a range sensor under each foot to detect distance of each foot to the ground while walking. I have generated a motion for my robot and I am testing it in choreonoid. My problem is sometimes during the simulation the range sensor doesn't recognize the ground and detect somewhere almost 20 cm lower than actual ground. It usually happens when foot and ground contact point moves slightly. So I am not sure if this is a contact issue or range sensor issue. I have attached a video which shows my problem. The small white dots that you see are the range sensor data for both feet and somewhere in the middle range sensor data of right leg change by small movement in contact point of right leg. Do you have any idea how to fix it?

[choreonoid1-2019-10-22_12.05.37.mkv.zip](https://github.com/s-nakaoka/choreonoid/files/3757929/choreonoid1-2019-10-22_12.05.37.mkv.zip)

**Comment by s-nakaoka** [comment]
I watched the video, but I didn't really understand the problem. I think this question is too complex and beyond the scope of what we can address here.
