### ISSUE TITLE
SensorVisualizerの子アイテムのチェック状態が保存されない

### ISSUE THREAD

**Issue by hattorishizuko** [s-nakaoka/choreonoid#228]
アイテムツリービューでSensorVisualizerの子アイテムにチェックを入れてプロジェクトを保存すると、チェックの有無が保存されないようになってしまいました。
再現方法は、TankVisionSensors.cnoidを読み込んで、そのままプロジェクトを保存。
再度プロジェクトを読み込むと、kinectなどのチェックがはずれてしまいます。

**Comment by s-nakaoka** [comment]
本件修正しました。 049ccbbb
