### ISSUE TITLE
SimpleControllerのbuildにおいてエラーになる

### ISSUE THREAD

**Issue by YoheiKakiuchi** [s-nakaoka/choreonoid#23]
`/usr/include/choreonoid-1.5/cnoid/SimpleController`をincludeすると、
`/usr/include/choreonoid-1.5/cnoid/src/SimpleControllerPlugin/library/SimpleController.h`を読みに行くようですが、
`/usr/include/choreonoid-1.5/cnoid/src/SimpleControllerPlugin/library`にはexportdecl.h がなくエラーになります。
ソースには存在しているようです。

**Comment by s-nakaoka** [comment]
本件対応しました。

**Comment by YoheiKakiuchi** [comment]
ありがとうございます。
