### ISSUE TITLE
cant find AGX dynamics dlls in run time

### ISSUE THREAD

**Issue by hazimian** [s-nakaoka/choreonoid#238]
Hi There
I have built the source code on Windows 10 and seemed to be working fine. However when I built with AGX dynamics  2.26 enabled and ran Choreonoid, I got the following error message in Choreonoid UI console. It looks like it cant find some AGX dlls. while when I checked they are actually there. Any help will be appreciated.

 The Eigen library version 3.2.10 is used (SIMD intruction sets in use: SSE, SSE2).
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXBodyExtensionPlugin.dll"
Error: Cannot load library C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXBodyExtensionPlugin.dll: The specified module could not be found.
Error: Loading the plugin failed.
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXDynamicsPlugin.dll"
Error: Cannot load library C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXDynamicsPlugin.dll: The specified module could not be found.
Error: Loading the plugin failed.
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidBalancerPlugin.dll"
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidBodyPlugin.dll"
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidPoseSeqPlugin.dll"
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXBodyExtensionPlugin.dll"
Error: Cannot load library C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXBodyExtensionPlugin.dll: The specified module could not be found.
Error: Loading the plugin failed.
Detecting plugin file "C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXDynamicsPlugin.dll"
Error: Cannot load library C:\Program Files\Choreonoid\lib\choreonoid-1.8\CnoidAGXDynamicsPlugin.dll: The specified module could not be found.
Error: Loading the plugin failed.
Body customizer "C:\Program Files\Choreonoid\lib\choreonoid-1.8\customizer\Labo1Customizer.dll" for Labo1 has been loaded.
Body-plugin has been activated.
PoseSeq-plugin has been activated.
Balancer-plugin has been activated.
OpenGL 3.3 (Intel Intel(R) UHD Graphics 630, GLSL 3.30 - Build 26.20.100.7528) is available for the "Scene" view.

**Comment by s-nakaoka** [comment]
https://discourse.choreonoid.org/t/agx-dynamics-error/378
