### ISSUE TITLE
メッセージビューでCtrl+Cが効かない

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#27]
ChoreonoidのメッセージビューでCtrl+Cが効きません．右クリックのポップアップメニューで，クリップボードへのコピーはできます．メニューには「Copy Ctrl+C」と書いてありますが，キーではできません．同じ位置にある，Pythonコンソールでは，Ctrl+Cが効きます．これを書いていて気づきましたが，Select AllのCtrl+Aも効きません．

**Comment by s-nakaoka** [comment]
すみません、だいぶ前に対応していたのですが、こちらで報告していませんでした。最新版ではどちらも効くようになっています。
