### ISSUE TITLE
BodyRTCの設定ファイルの指定について

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#28]
BodyRTCの設定ファイルをカレントディレクトリに置きたく，ファイルの場所をフルパスで/a/b/c/d.conf と書きました（パス名は仮のものです．/a/b/cがカレントディレクトリ）．メッセージビューにはそのファイルが読み込まれたと表示されます．プロジェクトを保存し，Choreonoidを再起動すると，BodyRTCのプロパティの設定ファイル名は，/a/b/c/d.conf ではなく，d.conf になっており，メッセージビューには，「"/usr/lib/choreonoid-1.5/rtc/ｄ.conf"　は存在しないか、開けません。」と表示されます．

使いにくいと思うのですが，どういう意図でこのような仕様になっているのでしょうか？

**Comment by s-nakaoka** [comment]
こちらも修正しておりました。よろしくお願いします。
