### ISSUE TITLE
ボディモーションの自動更新

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#29]
ボディモーションを自動更新にしていた場合，起動時にポーズからモーションを生成するようにしていただけませんか．それを忘れていて，戸惑うことが何度となくあります．

**Comment by s-nakaoka** [comment]
起動時にポーズ列データ(PoseSeqItem）からその小アイテムの動作軌道(BodyMotionItem)を生成するようにしました。

なお、生成するか否かの設定はプロジェクトごとに切り替えることができます。
メインメニューの「オプション」-「ポーズ列処理」-「Automatic Generation for a New Body」のチェックを切り替えて、プロジェクトを保存します。

キーポーズデータの長さや生成手法の設定によっては、動作軌道の生成に時間がかかることがあり、さらにそのようなデータが複数読み込まれる場合、プロジェクトの読み込みが遅くなってしまう可能性があります。そのような時には上記のチェックを外して、読み込み後に必要な部分だけ生成するようにしてください。（もともとHRP-4Cのダンスやデモを作成するときにそのような状況があったので、今まで自動生成はしないようにしていました。）

**Comment by y-masutani** [comment]
JVRCの掲示板では既に返信いたしましたが，対応していただきありがとうございました．
