### ISSUE TITLE
シミュレーション用Pythonスクリプトの停止

### ISSUE THREAD

**Issue by y-masutani** [s-nakaoka/choreonoid#30]
シミュレーションの実行を停止した際に，バックグラウンドで実行しているシミュレーション用Pythonスクリプトを停止させるようにできないでしょうか？

**Comment by s-nakaoka** [comment]
すみません、今更ではありますが、SimulatorItemのsigSimulationFinishedシグナルを使えばできるのではないかと思います。Pythonからも利用できます。
