### ISSUE TITLE
RTCアイテムでRTCのパスを絶対パスで入力しても相対に変換されてしまう

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#43]
BodyRTCアイテムでも同様の指摘があったと思います。
相対パスにしてしまうと、ロードに失敗し、Choreonoidが落ちるようです。
相対パスに勝手に変換しない、というのとロードに失敗してもChoreonoidは落ちないようにする対処が必要かと思います。

**Comment by s-nakaoka** [comment]
修正しました。

> BodyRTCアイテムでも同様の指摘があったと思います。

とのことですが、そちらについては症状を確認できませんでした。

**Comment by fkanehiro** [comment]
はい、BodyRTCについては指摘を受けて服部さんが既に対応済みです。

2015年10月7日 1:41 s-nakaoka <notifications@github.com>:
