### ISSUE TITLE
cnoidファイルとモデルファイルで関節数に矛盾があるとChoreonoidが落ちる

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#46]
モデルファイルを編集して関節数が変わったのに以前のcnoidファイルを流用したりするとChoreonoidが落ちます。落ちずに警告を出してくれると嬉しいです。

**Comment by s-nakaoka** [comment]
修正しました。
https://github.com/s-nakaoka/choreonoid/commit/984e766631c7b7d558f0adbd21b0cae763438bd9

**Comment by fkanehiro** [comment]
確認しました。
