### ISSUE TITLE
モデルを読み込んだらデフォルトで表示して欲しい

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#50]
現状モデルを読み込んでもチェックを入れないと表示されませんが、デフォルトでチェックを入れるようにすると何か不都合ありますでしょうか。デフォルトで表示された方が使い勝手がよいと思うのですが。

**Comment by s-nakaoka** [comment]
アイテムを読み込むときのダイアログに「アイテムツリービューのチェックを入れる」というオプションを設置しました。これをオンにしておくと、読み込み時にデフォルトでチェックが入るようになります。この設定はChoreonoid全体のコンフィグとしてコンフィグファイルに書き込まれますので、オンにする操作は一度行っておけばOKです。また、オン・オフの記録はアイテムの種類ごとに分けて行われます。

**Comment by fkanehiro** [comment]
ありがとうございます。確認しました。

**Comment by fkanehiro** [comment]
本件について、デフォルトをオンにしてはどうか、との意見が
jvrc/tutorials#9
にありましたのでお知らせします。
