### ISSUE TITLE
MovieGeneratorで画像の幅は記憶されるが高さは記憶されない

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#53]
ＭｏｖｉｅＧｅｎｅｒａｔｏｒで画像のサイズをデフォルトから変えると、幅は記憶されますが、高さは記憶されないようです。

**Comment by s-nakaoka** [comment]
MovieGeneratorの改良版としてMoveRecorderを開発しました。そちらでは直っているかと思います。

**Comment by fkanehiro** [comment]
ありがとうございます。確認しました。
