### ISSUE TITLE
可動範囲を設定していない関節があると関節スライダが使えなくなる

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#59]
可動範囲として非常に大きな値が入るせいか、スライダが表示されなくなります。

**Comment by s-nakaoka** [comment]
回転関節については、可動範囲を設定していないと+/-360度の可動範囲となるようにしています。
なので、このissueの対象は並進関節なのではないかと思いますが、それでよろしいでしょうか？
並進関節については、回転と違って一周で区切ることができず、モデルには様々なスケールがあり得るので、可動範囲のデフォルト値を設定したところで、あまり意味がなくなります。
なのでモデルの特に並進関節については可動範囲を設定していただく必要があります。

**Comment by s-nakaoka** [comment]
可動範囲を設定していない並進関節があると、可動範囲を示すラベルが大きくなりすぎて、それで他の関節まで使えなくなってしまうのですね。
これについては、値の大きさによってラベルのフォーマットを切り替えるようにして、対処しました。
https://github.com/s-nakaoka/choreonoid/commit/d7cf8b736b0be13b9ab2acf9010d19ff26fcfd1e

**Comment by fkanehiro** [comment]
確認しました。
ありがとうございます。
