### ISSUE TITLE
MovieGeneratorで対象ビューを選択しわすれていることをわかりやすくする

### ISSUE THREAD

**Issue by fkanehiro** [s-nakaoka/choreonoid#62]
対象ビューを選択するのをわすれていても特に怒られないので、正常に動作しない理由がわかりづらい

**Comment by s-nakaoka** [comment]
了解です。
実は今マニュアルの続きを書いていて、説明の図を作るためMovieGeneratorを使う必要が有り、ちょうど同じことを考えていました。うまくいくか分かりませんが、試してみます。

**Comment by s-nakaoka** [comment]
MovieGeneratorを改良してMovieRecorder(動画レコーダ）としました。
設定ダイアログの「対象ビュー」のコンボボックスで対象のビューを指定します。
「マーカ表示」にチェックを入れておくと、対象ビューを赤枠で囲い、録画時にはこれが点滅します。

**Comment by fkanehiro** [comment]
ありがとうございます。
